version: '3.7'

services:
  web:
    build: .
    volumes:
      - .:/app
    command: uvicorn app.api:app --reload --workers 1 --host 0.0.0.0 
    ports:
      - 8008:8000
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dbera
      - POSTGRES_PASSWORD=yourpword
      - POSTGRES_DB=testdatabase
    ports:
      - 5432:5432
volumes:
    postgres_data: